<?php

/**
 * @file
 * Support for legal agreement during user registration.
 */

/**
 * Implementation of hook_user().
 */
function legalagree_user($op, &$edit, &$user, $category = NULL) {
  switch($op) {
    // User is registering.
    case 'register':
      // Add a fieldset containing radio buttons to the
      // user registration form.
      $fields['terms_conditions'] = array(
        '#type' => 'fieldset',
        '#title' => t('Terms &amp; Conditions')
      );
      $fields['terms_conditions']['decision'] = array(
        '#type' => 'radios',
        '#description' => t('By registering at %site-name, you agree to the <a target="_blank" href="/terms-and-conditions">Terms &amp; Conditions</a> of this site.',
array('%site-name' => variable_get('site_name', 'drupal'))),
        '#default_value' => 0,
        '#options' => array(t('I disagree'), t('I agree'))
      );
      return $fields;

    // Field values for registration are being checked.
    // (also called when user edits his/her 'my account' page, but
    // $edit['decision'] is not set in that case).
    case 'validate':
      // Make sure the user selected radio button 1 ('I agree').
      // the validate op is reused when a user updates information on
      // the 'my account' page, so we use isset to test whether we are
      // on the registration page where the decision field is present.
      if (isset($edit['decision']) && $edit['decision'] != '1') {
        form_set_error('decision', t('You must agree to the Terms &amp; Conditions
          before registration can be completed.'));
      }
      break;

    // New user has just been inserted into the database.
    case 'insert':
      // Record information for future lawsuit.
      watchdog('user', t('User %user (UserID: %uid) agreed to legal terms',
        array('%user' => $user->name, '%uid' => $user->uid)));
      break;
  }
}
